---
# Scala

- name: Scala | Download Activator
  get_url: url=http://downloads.typesafe.com/typesafe-activator/{{ scala_activator_version }}/typesafe-activator-{{ scala_activator_version }}.zip dest=/root/activator.zip mode=0440

- name: Scala | Unzip Activator
  shell: unzip /root/activator.zip -d /root

- name: Scala | Install Activator
  shell: cp /root/activator-{{ scala_activator_version }}/activator* /usr/local/bin

- name: Scala | Set Binary Permissions
  file: path=/usr/local/bin/activator mode=0755
