---
# Update Apt Repository

- name: System | Update repository
  apt: update_cache=yes

# Python Requirements

- name: System | Install python-software-properties
  apt: pkg=python-software-properties state=installed

- name: System | Install Build-Essentials
  apt: pkg=build-essential state=installed

# ACL - for easy access control management

- name: System | Install ACL
  apt: pkg=acl state=installed

# cURL

- name: System | Install cURL
  apt: pkg=curl state=installed

# Git

- name: System | Install Git
  apt: pkg=git-core state=installed

# Host Configuration

- name: System | Set the hostname /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: System | Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: System | Copy the hosts file into place
  template: src=../files/hosts dest=/etc/hosts mode=0600
